### PR TITLE
doc update for SageMaker preview

### PR DESCRIPTION
**Pull request by surajkota**
Description of changes:
Update website with SageMaker release status

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by RedbackThomson** [comment]
Also need to update the SageMaker section below:

https://github.com/aws-controllers-k8s/community/blob/b7d3c9deda8c81406aa3666f0eab67b0391aea99/docs/contents/services.md#amazon-sagemaker

**Comment by surajkota** [comment]
@RedbackThomson, good catch! Updated

**Pull request merged**
