### PR TITLE
Add docs on drift remediation

### PR DESCRIPTION
**Pull request by jkatz**
Issue #, if available:

Description of changes: Add docs on drift remediation

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

Signed-off-by: Jonathan S. Katz <jkatz@amazon.com>

### CODE REVIEW

**Review by vijtrip2 — APPROVED** [review]

**Comment by vijtrip2** [comment]
Thank you, @jkatz !! I will let Amine/Jay give it another look and merge.

**Review by A-Hilaly — APPROVED** [review]
Niice!
Thinking that it might usefull to be able to set this value using a flag or env/var

**Review by jaypipes — APPROVED** [review]
Nice wording @jkatz thank you!

**Pull request merged**
