### PR TITLE
Minor tweaks to headings in "Understanding generator.yaml configuration"

### PR DESCRIPTION
**Pull request by jljaco**
Issue #, if available: N/A

Description of changes:
Made some small additions to the headings in this document to make the TOC easier to navigate

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jaypipes — APPROVED** [review]
ooooh, yeah, I like this. Nice! :)

**Review by RedbackThomson — APPROVED** [review]
Yeah these are super cute changes. I love it

/lgtm

**Review by A-Hilaly — APPROVED** [review]
++++
/lgtm

**Comment by A-Hilaly** [comment]
come on prow
/lgtm

**Pull request merged**
