### PR TITLE
Generate services page using `ackdiscover`

### PR DESCRIPTION
**Pull request by RedbackThomson**
Description of changes:
Generates the `services.md` page in the community documentation using the utility methods from `ackdiscover`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by RedbackThomson** [comment]
/hold
Waiting for `ackdiscover` so we can add it to `requirements.txt`

**Review by jaypipes — APPROVED** [review]
:partying_face: Heck yeah, @RedbackThomson, you have the vision! :)

**Comment by RedbackThomson** [comment]
/unhold
Should be good to go, now!

**Pull request merged**
