### PR TITLE
Update command to retrieve Sagemaker controller version

### PR DESCRIPTION
**Pull request by ananth102**
Description of changes:

Dynamically retrieve the latest version of the Sagemaker controller instead of hardcoding, script is borrowed from https://aws-controllers-k8s.github.io/community/docs/user-docs/install/.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jljaco — COMMENTED** [review]
I'm ambivalent about this method of obtaining the most recent release version.  

On the one hand, it's obviously more maintainable.

On the other, the GH API is frequently unavailable; for example, I just attempted to retrieve this value now and got:

```
 $ curl -sL https://api.github.com/repos/aws-controllers-k8s/sagemaker-controller/releases/latest 
{"message":"API rate limit exceeded for XXXXXXXX. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

Could you perhaps split this command pipeline into 2 distinct steps with an error check in between to verify that the user has gotten a valid tag value?

**Review by surajkota — COMMENTED** [review]
lets do the same for application autoscaling tutorial as well

**Review by A-Hilaly — APPROVED** [review]
Niice, i like it!
/lgtm

**Review by A-Hilaly — COMMENTED** [review]
Can you also add `curl` to the list of requirements?

**Comment by ananth102** [comment]
> Can you also add `curl` to the list of requirements?

Sure will do

**Pull request merged**
